server:
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wiki?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: wiki
    password: 123456

# 自定义配置
test:
  hello: Hello
# 日志级别
#logging:
#  level:
#    root: debug
mybatis:
  # mapper.xml路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 别名映射包路径
  type-aliases-package: com.yum.wiki.domain
