# Get请求
GET http://localhost:8081/ebook/list?page=1&size=1001
Accept: application/json

###
GET http://localhost:8081/ebook/search?text=vue&page=1&size=1000
Accept: application/json
# 多个测试脚本需要用###隔离
###



###
# POST请求
POST http://localhost:8081/ebook/save
Content-Type: application/json

{

}

###
# PUT请求


# Delete请求
