# Get请求
GET http://localhost:8081/hello
#Accept: application/json

# 结果验证脚本
> {%
 client.test("test-hello", function() {
   client.log("测试/hello接口");
   client.log(response.body);
   client.log(JSON.stringify(response.body)); // 虽然idea没有提示JSON，但是可以用
   client.assert(response.status === 200, "返回码不是200");
   client.assert(response.body === "Hello World", "结果验证失败");
 });
%}

###

# 多个测试脚本需要用###隔离
###



###
# POST请求
POST http://localhost:8081/hello/post
Content-Type: application/x-www-form-urlencoded

name=text

###
# PUT请求


# Delete请求
